name: mp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.4.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path:
  ffi:
  markdown_widget: ^2.3.2+6
  fl_chart: ^0.69.0
  dart_eval: ^0.7.9
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/